// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBX2HcbG2m5zTKeAVssOCzQFR3FaULgeE',
    appId: '1:1002004893158:web:b503302ea949c7640b9a27',
    messagingSenderId: '1002004893158',
    projectId: 'avaliacao-fibra',
    authDomain: 'avaliacao-fibra.firebaseapp.com',
    storageBucket: 'avaliacao-fibra.firebasestorage.app',
    measurementId: 'G-XHYCTLFTDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_u4Hg_p3Xe3PWX8H3F8nyrA-WWJUCeM4',
    appId: '1:1002004893158:android:7f08b42388095b720b9a27',
    messagingSenderId: '1002004893158',
    projectId: 'avaliacao-fibra',
    storageBucket: 'avaliacao-fibra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKoAvULLA15epszlp7owZi-CvXkLql1Sk',
    appId: '1:1002004893158:ios:b4ef70f74206cfcc0b9a27',
    messagingSenderId: '1002004893158',
    projectId: 'avaliacao-fibra',
    storageBucket: 'avaliacao-fibra.firebasestorage.app',
    iosBundleId: 'com.example.gasolina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKoAvULLA15epszlp7owZi-CvXkLql1Sk',
    appId: '1:1002004893158:ios:b4ef70f74206cfcc0b9a27',
    messagingSenderId: '1002004893158',
    projectId: 'avaliacao-fibra',
    storageBucket: 'avaliacao-fibra.firebasestorage.app',
    iosBundleId: 'com.example.gasolina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBX2HcbG2m5zTKeAVssOCzQFR3FaULgeE',
    appId: '1:1002004893158:web:262de65c15e47e610b9a27',
    messagingSenderId: '1002004893158',
    projectId: 'avaliacao-fibra',
    authDomain: 'avaliacao-fibra.firebaseapp.com',
    storageBucket: 'avaliacao-fibra.firebasestorage.app',
    measurementId: 'G-H151ZGVWRF',
  );
}
